### ISSUE TITLE
gptq quantization fails ModuleNotFoundError

### ISSUE THREAD

**Issue by escorciav** [Lightning-AI/lit-parrot#113]
Dear team,

Thanks a lot for reducing the barrier of entrance to work & use open-source LLMs. I was not able to quantize a 2.4B model with gptq for my modest RTX2080.
I got the following error

```bash
python quantize/gptq.py --checkpoint_dir checkpoints/EleutherAI/pythia-2.8b-deduped --dtype bfloat16
Loading model 'checkpoints/EleutherAI/pythia-2.8b-deduped/lit_model.pth' with {'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 128, 'padded_vocab_size': 50304, 'n_layer': 32, 'n_head': 32, 'n_embd': 2560, 'rotary_percentage': 0.25, 'parallel_residual': True, 'bias': True, 'n_query_groups': 32, 'shared_attention_norm': False}
Time to load model: 9.79 seconds.
Traceback (most recent call last):
  File "/awesome-project/lit-parrot/quantize/gptq.py", line 376, in <module>
    CLI(main)
  File "/env/lib/python3.10/site-packages/jsonargparse/cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/env/on-device-llm/lib/python3.10/site-packages/jsonargparse/cli.py", line 147, in _run_component
    return component(**cfg)
  File "/awesome-project/lit-parrot/quantize/gptq.py", line 357, in main
    test_string = get_sample_data()
  File "/awesome-project/lit-parrot/quantize/gptq.py", line 214, in get_sample_data
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'
```

The issue may be related to the module (package?) `datasets`. Could you kindly provide a pointer to fix it? 

Thanks in advance!

**Comment by escorciav** [comment]
It might work after running, `pip install datasets`. Refer to [this doc](https://huggingface.co/docs/datasets/installation#pip) for more details.

**Comment by lsc64** [comment]
I think this should be re-opened and closed when added to requirements.txt

**Comment by escorciav** [comment]
Sure, I have an environment setup. Just lemme know, and I'm happy to try again :blush: 

BTW, I'm not sure if the issue is due to an "old" GPU (RTX2080). As the requirements of my project changed: export any (L)LM to onnx with opset 9, I dropped off lit-parrot. I'm working directly with `transformers` and `optimum`. If you provide support for T5, I'm happy to keep playing with LIT-:parrot: 

cc @rasbt

**Comment by rasbt** [comment]
Thanks for pointing this out and sharing @escorciav 

I am pretty certain that the RTX2080 only supports float16 but not bfloat16 training. Bfloat16 is a relatively recent feature for NVIDIA cards. The RTX 3000 series (and A100 etc.) would support it.

(The alternative here would be to run it with `float16` instead of `bfloat16`
