### ISSUE TITLE
Why have a default max_seq_length of 256?

### ISSUE THREAD

**Issue by iskandr** [Lightning-AI/lit-parrot#122]
I noticed that both the data prep / tokenization script (https://github.com/Lightning-AI/lit-parrot/blob/main/scripts/prepare_alpaca.py#L26) and the fine-tuning scripts (https://github.com/Lightning-AI/lit-parrot/blob/main/finetune/adapter.py#L41, https://github.com/Lightning-AI/lit-parrot/blob/main/finetune/adapter_v2.py#L46) have `max_seq_length=256`. 

While this does seem to speed up tokenization it has the unfortunate property of truncating fine-tuning inputs and also requiring someone to change both scripts to use the full context length of a language model. I'm curious why this parameter got added and whether it might be possible to switch to a default of `None` or 4096?

**Comment by carmocca** [comment]
That is a good observation. I agree that we should remove the `max_seq_length` value passed to the model forward and separate it from the max_length used to split the dataset.

I don't know why this was chosen originally. Perhaps a mixup.

Would you be interested in opening a PR?

**Comment by iskandr** [comment]
Sure, let me take a look tomorrow

**Comment by lantiga** [comment]
Yes, definitely! Great idea, thanks @iskandr

**Comment by iskandr** [comment]
Started a PR (https://github.com/Lightning-AI/lit-parrot/pull/127/) but still have to actually test that it doesn't change or break anything.
