### ISSUE TITLE
RoPE precision issue

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lit-parrot#13]
One of the CUDA tests is failing: `pytest tests/test_model.py::test_bfloat16_llama_init`

```python
E       RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: float key.dtype: float and value.dtype: c10::BFloat16 instead.
```

I think there's a bug in how the dtype is managed in rope

_Originally posted by @carmocca in https://github.com/Lightning-AI/lit-stablelm/pull/11#discussion_r1186292614_

**Comment by carmocca** [comment]
Adding

```python
    roped = (x * cos) + (rotated * sin)
    return roped.type_as(x)
```

Fixes the error above, but the test still fails. Generation looks fine though

**Comment by carmocca** [comment]
cc @t-vi, maybe you can catch this bug easily as you wrote this test originally

**Comment by t-vi** [comment]
I'm not entirely sure, it could be that the tolerance is somewhat tight, but I have not checked in great detail what I'd expect for bf16.
