### ISSUE TITLE
Code refactoring for finetuning

### ISSUE THREAD

**Issue by nishnik** [Lightning-AI/lit-parrot#163]
Hi @carmocca 

A lot of code for `fintune/adapter.py`, `fintune/adapter_v2.py`, `fintune/lora.py` is common, like `setup`, `main`, `train`, `validate`, `loss_fn`, `get_batch` and `save_model_checkpoint`. There is only a little bit of change for specific finetuning method. So if we need to change `get_batch`, we need to change all files. 

Should we create a `fintune/fintuner.py` which will have a `BaseFinetuner` class with all these functions? Then different finetuning methods can inherit this class. 

cc @rasbt

**Comment by carmocca** [comment]
You are right, 90% of the code in the fine-tuning and pertaining scripts is exactly the same.

However, this project's README says

> Avoiding code duplication is not a goal. Readability and hackability are.

The intention is that you clone the repo and build on top of this. If we refactored everything into reusable components, then the code would be constraining you to use ours abstractions or to unroll them back into a single file.

Thank you for your suggestion nonetheless!
