### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch>=2.1.0dev

### ISSUE THREAD

**Issue by nestorvw** [Lightning-AI/lit-parrot#37]
Hello,

I have just cloned the repository and run `pip install -r requirements.txt` as explained in README.md file but I get following error:

```bash
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement torch>=2.1.0dev (from versions: 2.0.0)
ERROR: No matching distribution found for torch>=2.1.0dev
```
I already tried following commands with same result:

```
pip install --pre -r requirements.txt
pip install --pre -r requirements.txt -f https://download.pytorch.org/whl/nightly/cpu
```

The issue is because nightly `dev` version of `torch` is not found and not installed.
Am I missing something?
I am running on a MacBook Pro Apple M1 Max

Thanks,
Nestor

**Comment by lantiga** [comment]
Can you try opening requirements.txt and replacing 
```
--extra-index-url https://download.pytorch.org/whl/nightly/cu118 --pre
```

with

```
--extra-index-url https://download.pytorch.org/whl/nightly/cpu --pre
```
?

**Comment by lantiga** [comment]
We changed the install instructions so this is clearer. Closing for now, feel free to reopen.
