### ISSUE TITLE
Pythia embedding dimension mismatch

### ISSUE THREAD

**Issue by rcmalli** [Lightning-AI/lit-parrot#50]
I have encountered some errors while downloading these models and converting their weights from Huggingface:

- `pythia-1b`
- `pythia-1.4b`
- `pythia-2.8b` 

Their embedding dimensions are not correctly specified inside huggingface repository. For example:

- `pythia-1b` model expects `n_embd=8192` but the actual weight dimension is 2048.
- `pythia-1.4b` model expects `n_embd=8192` but the actual weight dimension is 2048. 
- `pythia-2.8b` model expects `n_embd=8192` but the actual weight dimension is 2560.

I also checked their original repository on [EleutherAI/pythia](https://github.com/EleutherAI/pythia/tree/main/models) and numbers are aligned with `hidden-size` parameter inside the configuration file of each model. Configuration files on Hugginface repository might be wrong. Have you ever checked these models?

Here is an example error:

![image](https://github.com/Lightning-AI/lit-parrot/assets/7341604/b5dbd451-e64d-4d17-a9d0-7673f0865248)

Note: It is same for both `deduped` and original models and I didn't try models larger than 2.8b from Pythia repository.

**Comment by carmocca** [comment]
You are right! I must've messed something when copying over the configs. Thank you for reporting
