### ISSUE TITLE
Cached KVs not implemented on Adapter causing errors.

### ISSUE THREAD

**Issue by bkiat1123** [Lightning-AI/lit-parrot#58]
Adapter inherits most methods from the BaseModel.  The Adapter's init method, Block's forward method and CausalSelfAttention's forward method didn't implement the Cached KVs logics, causing errors.

The errors are mostly from forward method in Adapter.
Example:
```python
AttributeError: 'Parrot' object has no attribute 'rope_cache' 
TypeError: Block.forward() takes 2 positional arguments but 7 were given
```

We should add 

- rope_cache, mask_cache, kv_caches attributes to Adapter init method.
- rope, mask, max_seq_length, input_pos, kv_cache to input of Block and CausalSelfAttention forward method
- return kv_cache in  Block and CausalSelfAttention forward method

**Comment by RDouglasSharp** [comment]
See my comment - issue is that Adapter is inheriting from incorrect baseclass

**Comment by RDouglasSharp** [comment]
I mean I added it as a new issue, but I believe it is the fix for this issue
