### ISSUE TITLE
Should `huggingface_hub` be added to requirements.txt?

### ISSUE THREAD

**Issue by emilesilvis** [Lightning-AI/lit-parrot#96]

**Comment by emilesilvis** [comment]
Makes sense! If desired, I can edit the README to add `pip install huggingface_hub` where required.

**Comment by carmocca** [comment]
Good idea. But you should add it to the `howto`s about downloading data, not the README

**Comment by emilesilvis** [comment]
https://github.com/Lightning-AI/lit-parrot/pull/97

**Comment by nahakiole** [comment]
I ran into the issue after following the tutorial here again: https://lightning.ai/pages/blog/falcon-a-guide-to-finetune-and-inference/

Maybe a idea would be to use the `extras_require` feature in the setup.py and create multiple versions?

```
extras_require={
    'download':  ['huggingface_hub'],  # These are additional requirements for the "download" version
},
```

Then we could add `pip install .[download]` to the documentation.
I think it would be important to add this in the main readme.md.
